name: Automated Preprocessing

on:
  push:
    branches:
      - main

jobs:
  preprocess-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Preprocessing Script
        run: |
          python preprocessing/automate_Daffa-Bagus-Maulana.py

      - name: Commit Processed Data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add preprocessing/heartdisease_preprocessing.csv

          git commit -m "Update processed dataset" || echo "No changes to commit"

          git push